[project]
name = "the-mighty-function"
version = "0.1.0"
description = ""
requires-python = "~=3.12"
readme = "README.md"
license = "MIT"
dependencies = []
[[project.authors]]
name = "Andreas Bergman"
email = "andreas@arjancodes.com"

[tool.pylint."MESSAGES CONTROL"]
disable = [ "missing-class-docstring", "missing-function-docstring", "missing-module-docstring",]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]


