[project]
name = "app"
version = "0.1.0"
description = ""
requires-python = "~=3.11"
readme = "README.md"
license = "MIT"
dependencies = []
[[project.authors]]
name = "Andreas Bergman"
email = "andreas@arjancodes.com"

[tool.pytest.ini_options]
pythonpath = [ ".", "src",]
addopts = [ "--import-mode=importlib",]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
